nginx:
  build: ./nginx
  ports: 
    - 80:80
    - 443:443
  links:
    - php56
  volumes_from:
    - code
  volumes:
    - ./nginx/sites:/etc/nginx/sites-enabled
    - ./nginx/logs:/var/log/nginx:rw
  restart: always

mailhog:
  image: mailhog/mailhog
  expose:
    - "1025"
    - "8025"
  ports:
    - "8025:8025"

mysql57:
  build: ./mysql57
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: 12345
  volumes_from:
    - code
  volumes:
    - ./localdb/.db/mysql:/var/lib/mysql:rw

php56:
  build: ./php56
  volumes_from:
    - code
  links:
    - mysql57:db
    - mailhog:mail
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:rw
  environment:
    TERM: xterm

code:
  build: ./code
  volumes:
    - /home/funnyboy/data/work:/var/www/projects
  tty: true

phpmyadmin:
  build: ./phpmyadmin
  links:
    - mysql57:mysql
    - php56
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: 12345
    PMA_HOST: mysql


